.PHONY: clean All

All:
	@echo "----------Building project:[ ope - Debug ]----------"
	@cd "ope" && "$(MAKE)" -f  "ope.mk"
clean:
	@echo "----------Cleaning project:[ ope - Debug ]----------"
	@cd "ope" && "$(MAKE)" -f  "ope.mk" clean
